In [35]:
import importlib
import scraper as sc
importlib.reload(sc)
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')

plt.style.use('ggplot')

KeyboardInterrupt:

In [24]:
nsdq = sc.nsdq_tickers("nasdaq.csv")
posts_df = sc.fetch_submissions("wallstreetbets", 100)
posts_df = sc.post_extract_tickers(posts_df, nsdq)
posts_df.head(50)

,subreddit,submission_id,author,created_utc,title,body,url,selftext,score,num_comments,is_self,upvote_ratio,permalink,content,p_mentioned
0,wallstreetbets,1ne7muv,hv876,1757594117,August CPI,TL;DR numbers in line with expectation.\n\nYoY...,https://i.redd.it/6gp3dmpo5jof1.jpeg,TL;DR numbers in line with expectation.\n\nYoY...,8103,309,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,August CPITL;DR numbers in line with expectati...,[]
1,wallstreetbets,1ndwms0,Best_Fill2442,1757555760,OPEN gain porn 69k to 1 million,"As a ""not complicated retail investor"" who sim...",https://www.reddit.com/r/wallstreetbets/commen...,"As a ""not complicated retail investor"" who sim...",6909,919,True,0.93,https://www.reddit.com/r/wallstreetbets/commen...,"OPEN gain porn 69k to 1 millionAs a ""not compl...",[OPEN]
2,wallstreetbets,1ndussy,Bonghead13,1757550332,Happy birthday to me! It's not crazy money lik...,,https://i.redd.it/g3vrv3qhjfof1.jpeg,,3181,257,False,0.98,https://www.reddit.com/r/wallstreetbets/commen...,Happy birthday to me! It's not crazy money lik...,[ORCL]
3,wallstreetbets,1nejnun,Key_Song4837,1757622518,$OPEN Millionaire,I cried from laughing when I sold all of my NV...,https://www.reddit.com/gallery/1nejnun,I cried from laughing when I sold all of my NV...,1679,166,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,$OPEN MillionaireI cried from laughing when I ...,[OPEN]
4,wallstreetbets,1neavmn,DalaDanny,1757602229,$OPEN ... My First >10x Bagger ... Makes sense...,,https://i.redd.it/toml7uaqtjof1.png,,874,131,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,$OPEN ... My First >10x Bagger ... Makes sense...,[OPEN]
5,wallstreetbets,1ndwegw,sw3d,1757555062,500 -> 100k,DD: SNPS is a relatively unknown name in AI bu...,https://www.reddit.com/gallery/1ndwegw,DD: SNPS is a relatively unknown name in AI bu...,820,212,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,500 -> 100kDD: SNPS is a relatively unknown na...,"[AI, SNPS, DD]"
6,wallstreetbets,1nec6an,duddnddkslsep,1757605327,buy OPEN while you still can,,https://i.redd.it/oc82ak9x2kof1.jpeg,,832,527,False,0.84,https://www.reddit.com/r/wallstreetbets/commen...,buy OPEN while you still can,[OPEN]
7,wallstreetbets,1nebczs,SilbergleitJunior,1757603386,Subprime Auto Lender Collapse Delivers Blow to...,,https://i.redd.it/hw1qqljrwjof1.jpeg,,741,134,False,0.97,https://www.reddit.com/r/wallstreetbets/commen...,Subprime Auto Lender Collapse Delivers Blow to...,[]
8,wallstreetbets,1ndv3dq,Tizz_GGC,1757551207,Congrats to you ORCL folks but I hate you,I was so close to becoming an overnight millio...,https://www.reddit.com/r/wallstreetbets/commen...,I was so close to becoming an overnight millio...,689,188,True,0.91,https://www.reddit.com/r/wallstreetbets/commen...,Congrats to you ORCL folks but I hate youI was...,[ORCL]
9,wallstreetbets,1ne9b4h,newmoneyking,1757598516,OPEN,"Biggest profit have ever made in my life, I’m ...",https://i.redd.it/r0ohi0jrijof1.jpeg,"Biggest profit have ever made in my life, I’m ...",654,126,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,"OPENBiggest profit have ever made in my life, ...",[]
10,wallstreetbets,1ne7y85,SPXQuantAlgo,1757594971,CPI hotter than expected - 0.4% MoM,,https://i.redd.it/dgp3bz288jof1.jpeg,,352,130,False,0.93,https://www.reddit.com/r/wallstreetbets/commen...,CPI hotter than expected - 0.4% MoM,[]
11,wallstreetbets,1neaohr,ImSoEra,1757601756,Just a thank you to everyone.,I put 1500 dollars in this year. It’s not much...,https://i.redd.it/w3gpn0hesjof1.jpeg,I put 1500 dollars in this year. It’s not much...,362,38,False,0.95,https://www.reddit.com/r/wallstreetbets/commen...,Just a thank you to everyone.I put 1500 dollar...,[DD]
12,wallstreetbets,1ned2hq,DirtyFatB0Y,1757607413,Is this what a ten bagger feels like?,Let’s see how far this baby goes before I have...,https://i.redd.it/d93kdm189kof1.jpeg,Let’s see how far this baby goes before I have...,287,49,False,0.95,https://www.reddit.com/r/wallstreetbets/commen...,Is this what a ten bagger feels like?Let’s see...,[]
13,wallstreetbets,1neb4q7,Puzzled_News_6631,1757602839,Blockchain backed home equity lender has gone ...,"Well it’s happening, home equity lender using ...",https://www.reddit.com/r/wallstreetbets/commen...,"Well it’s happening, home equity lender using ...",253,58,True,0.91,https://www.reddit.com/r/wallstreetbets/commen...,Blockchain backed home equity lender has gone ...,[]
14,wallstreetbets,1ne4rl4,wsbapp,1757584918,"Daily Discussion Thread for September 11, 2025",This post contains content not supported on ol...,https://www.reddit.com/r/wallstreetbets/commen...,This post contains content not supported on ol...,196,11697,True,0.92,https://www.reddit.com/r/wallstreetbets/commen...,"Daily Discussion Thread for September 11, 2025...",[]
15,wallstreetbets,1ndvgdr,ErectZombie,1757552272,Finaly hit a banger boys! $open go brrrrrr.,Sold my 5$ calls this morning and bought a bun...,https://i.redd.it/mgjvvzc9pfof1.jpeg,Sold my 5$ calls this morning and bought a bun...,166,20,False,0.93,https://www.reddit.com/r/wallstreetbets/commen...,Finaly hit a banger boys! $open go brrrrrr.Sol...,[]
16,wallstreetbets,1necftc,DrSeuss1020,1757605952,“Oh the Places You’ll Go”,Congrats to anyone else who bought when I did....,https://i.redd.it/j89ft2pv4kof1.jpeg,Congrats to anyone else who bought when I did....,177,37,False,0.94,https://www.reddit.com/r/wallstreetbets/commen...,“Oh the Places You’ll Go”Congrats to anyone el...,[]
17,wallstreetbets,1negqnr,Old-Chemistry-7050,1757615739,Either the best trade I’ve ever done or the worst,,https://i.redd.it/ezbt856zxkof1.jpeg,,172,141,False,0.90,https://www.reddit.com/r/wallstreetbets/commen...,Either the best trade I’ve ever done or the worst,[]
18,wallstreetbets,1nedg0a,DonaldPump1,1757608281,The Larry Play - Paramount Skydance $PSKY,**The Larry Ellison Play - Paramount Skydance ...,https://www.reddit.com/r/wallstreetbets/commen...,**The Larry Ellison Play - Paramount Skydance ...,150,125,True,0.94,https://www.reddit.com/r/wallstreetbets/commen...,The Larry Play - Paramount Skydance $PSKY**The...,"[BITF, PSKY]"
19,wallstreetbets,1ndta5h,livingisdeadly,1757546039,2800 percent give or take,I bought some Oracle contracts that were under...,https://i.redd.it/o49mfoqp6fof1.jpeg,I bought some Oracle contracts that were under...,123,10,False,0.96,https://www.reddit.com/r/wallstreetbets/commen...,2800 percent give or takeI bought some Oracle ...,[]
20,wallstreetbets,1ndvw6u,savior517,1757553555,"$4,440 off of 3 $20 contracts is ok...","I would have held longer, but I have a really ...",https://i.redd.it/3krifsn2tfof1.jpeg,"I would have held longer, but I have a really ...",124,19,False,0.93,https://www.reddit.com/r/wallstreetbets/commen...,"$4,440 off of 3 $20 contracts is ok...I would ...",[]
21,wallstreetbets,1nechnz,Apprehensive-Meat742,1757606077,Strong Year,,https://www.reddit.com/gallery/1nechnz,,129,22,False,0.92,https://www.reddit.com/r/wallstreetbets/commen...,Strong Year,[]
22,wallstreetbets,1ne9jto,Soldacki,1757599139,The door is always OPEN 🚪,"I forgot I had these in Robinhood, my main acc...",https://www.reddit.com/gallery/1ne9jto,"I forgot I had these in Robinhood, my main acc...",120,27,False,0.92,https://www.reddit.com/r/wallstreetbets/commen...,The door is always OPEN 🚪I forgot I had these ...,[OPEN]
23,wallstreetbets,1ndvlv0,SingleInitiative4598,1757552725,I'm tired boss,6 years of trading and I have never seen the g...,https://i.redd.it/opasepdupfof1.png,6 years of trading and I have never seen the g...,118,86,False,0.91,https://www.reddit.com/r/wallstreetbets/commen...,I'm tired boss6 years of trading and I have ne...,[TTD]
24,wallstreetbets,1nejj1y,RandomRocketScience,1757622205,"Shorting Open at 2.70, what could go wrong?",,https://i.imgur.com/PwSFKSI.png,,111,64,False,0.94,https://www.reddit.com/r/wallstreetbets/commen...,"Shorting Open at 2.70, what could go wrong?",[]
25,wallstreetbets,1neiuw5,wsbapp,1757620653,"What Are Your Moves Tomorrow, September 12, 2025",This post contains content not supported on ol...,https://www.reddit.com/r/wallstreetbets/commen...,This post contains content not supported on ol...,100,3013,True,0.93,https://www.reddit.com/r/wallstreetbets/commen...,"What Are Your Moves Tomorrow, September 12, 20...",[]
26,wallstreetbets,1ne8vin,Xtianus21,1757597412,$GLXY $CRWV- A massive deal for StarGate betwe...,StarGate is here and one does not just bring o...,https://www.reddit.com/r/wallstreetbets/commen...,StarGate is here and one does not just bring o...,76,23,True,0.94,https://www.reddit.com/r/wallstreetbets/commen...,$GLXY $CRWV- A massive deal for StarGate betwe...,"[FAST, AI, GPUS, CRWV, PR, NBIS, III, NVDA, PS..."
27,wallstreetbets,1neem6d,theadvancedip,1757610919,"550,000% gain",,https://www.reddit.com/gallery/1neem6d,,78,35,False,0.78,https://www.reddit.com/r/wallstreetbets/commen...,"550,000% gain",[]
28,wallstreetbets,1nec22b,Gravix202,1757605046,I OPEN RDDT everyday so it just made sense.,Plan for Reddit is to hold till $690 per share...,https://i.redd.it/obxksnn62kof1.jpeg,Plan for Reddit is to hold till $690 per share...,71,7,False,0.90,https://www.reddit.com/r/wallstreetbets/commen...,I OPEN RDDT everyday so it just made sense.Pla...,"[OPEN, RDDT]"
29,wallstreetbets,1neb7vz,julet0790,1757603042,Open gains,I posted a few weeks ago and everyone keeps as...,https://www.reddit.com/gallery/1neb7vz,I posted a few weeks ago and everyone keeps as...,62,9,False,0.90,https://www.reddit.com/r/wallstreetbets/commen...,Open gainsI posted a few weeks ago and everyon...,[]
30,wallstreetbets,1neh6bu,Immediate_Poem_7393,1757616750,Adobe is going down,"with chatgpt and AI, adobe losing its market d...",https://i.redd.it/w3cmv5iz0lof1.jpeg,"with chatgpt and AI, adobe losing its market d...",61,119,False,0.86,https://www.reddit.com/r/wallstreetbets/commen...,"Adobe is going downwith chatgpt and AI, adobe ...",[AI]
31,wallstreetbets,1nebkil,mynameisnotarthur,1757603897,Did I win?,,https://i.redd.it/w7arhflryjof1.jpeg,,52,4,False,0.91,https://www.reddit.com/r/wallstreetbets/commen...,Did I win?,[]
32,wallstreetbets,1neh4v2,JahonSedeKodi,1757616656,Thank you OPEN,,https://i.redd.it/jxefglfp0lof1.jpeg,,49,8,False,0.88,https://www.reddit.com/r/wallstreetbets/commen...,Thank you OPEN,[OPEN]
33,wallstreetbets,1ne7frn,BubblyObject5665,1757593570,RedCat because I LOVE the kitty 🐱,"\nSecretary of Defense, Hegseth’s drone domina...",https://i.redd.it/jonl5p724jof1.jpeg,"\nSecretary of Defense, Hegseth’s drone domina...",42,31,False,0.79,https://www.reddit.com/r/wallstreetbets/commen...,RedCat because I LOVE the kitty 🐱\nSecretary o...,"[AI, LOVE]"
34,wallstreetbets,1nejwwy,BigTipperTimmons,1757623105,$OPEN Dat Ass 🫱🍩🫲,,https://i.redd.it/i2y4nyqvjlof1.jpeg,,68,22,False,0.86,https://www.reddit.com/r/wallstreetbets/commen...,$OPEN Dat Ass 🫱🍩🫲,[OPEN]
35,wallstreetbets,1ne4993,Snipeyomom,1757582937,If war is high I’ll buy this portfolio is spon...,,https://i.redd.it/kpdmhlxf8iof1.jpeg,,45,18,False,0.75,https://www.reddit.com/r/wallstreetbets/commen...,If war is high I’ll buy this portfolio is spon...,[]
36,wallstreetbets,1nefzja,WingWorried6176,1757614019,PSKY to THE SKY,Had 200 of the $17 lottos and sold half for 5k...,https://i.redd.it/bqzc5a8vskof1.jpeg,Had 200 of the $17 lottos and sold half for 5k...,39,11,False,0.90,https://www.reddit.com/r/wallstreetbets/commen...,PSKY to THE SKYHad 200 of the $17 lottos and s...,[PSKY]
37,wallstreetbets,1necum1,bumpyclouds,1757606898,Had to liquidate,"Not massive, but a nice $20k to $70k in a few ...",https://i.redd.it/r0o94rwo7kof1.jpeg,"Not massive, but a nice $20k to $70k in a few ...",46,19,False,0.84,https://www.reddit.com/r/wallstreetbets/commen...,"Had to liquidateNot massive, but a nice $20k t...",[]
38,wallstreetbets,1ndwy3q,Mah_Name_Jef,1757556709,Options giant,I'm excited to wake up to another massive gain...,https://i.redd.it/3yhuzqdg2gof1.jpeg,I'm excited to wake up to another massive gain...,34,15,False,0.81,https://www.reddit.com/r/wallstreetbets/commen...,Options giantI'm excited to wake up to another...,[]
39,wallstreetbets,1ndzgow,Maleficent-Poem4349,1757564636,100k YOLO $NBIS AGAIN,"I think it’s gonna go up to 100 again, my gut ...",https://i.redd.it/pokih3r0qgof1.jpeg,"I think it’s gonna go up to 100 again, my gut ...",37,22,False,0.87,https://www.reddit.com/r/wallstreetbets/commen...,100k YOLO $NBIS AGAINI think it’s gonna go up ...,"[NBIS, GAINI]"
40,wallstreetbets,1ndxx56,Soft-Presentation-66,1757559665,Another Oracle Gain Post,,https://www.reddit.com/gallery/1ndxx56,,33,5,False,0.78,https://www.reddit.com/r/wallstreetbets/commen...,Another Oracle Gain Post,[]
41,wallstreetbets,1nef4cr,PaperHandsTheDip,1757612061,$LDI - Yolo,,https://i.redd.it/33hu2fgwmkof1.png,,29,31,False,0.82,https://www.reddit.com/r/wallstreetbets/commen...,$LDI - Yolo,[LDI]
42,wallstreetbets,1neeg9i,Upper_Blackberry_685,1757610546,The wheel strategy was the best thing that eve...,Nuff said,https://i.redd.it/uf9freejikof1.jpeg,Nuff said,38,24,False,0.90,https://www.reddit.com/r/wallstreetbets/commen...,The wheel strategy was the best thing that eve...,[]
43,wallstreetbets,1negxru,Blamurai,1757616210,LoanDepot: A Fork in the Road,Wtf is this company and what does it do? Loand...,https://www.reddit.com/r/wallstreetbets/commen...,Wtf is this company and what does it do? Loand...,28,17,True,0.80,https://www.reddit.com/r/wallstreetbets/commen...,LoanDepot: A Fork in the RoadWtf is this compa...,"[OPEN, UWMC, LDI, AI, RKT]"
44,wallstreetbets,1neg082,shoppingguy7,1757614063,Betting against the AI bubble,"Fellow retards, I don’t think the current bull...",https://i.redd.it/u8pi6btzskof1.jpeg,"Fellow retards, I don’t think the current bull...",34,74,False,0.75,https://www.reddit.com/r/wallstreetbets/commen...,"Betting against the AI bubbleFellow retards, I...",[AI]
45,wallstreetbets,1nej6r8,theviableredditor,1757621420,WE'RE IN THE CLUB,,https://www.reddit.com/gallery/1nej6r8,,25,9,False,0.81,https://www.reddit.com/r/wallstreetbets/commen...,WE'RE IN THE CLUB,[]
46,wallstreetbets,1nefw9m,Learn_The_Machines,1757613807,$PSKY $17 Calls Expiring Tomorrow,,https://i.redd.it/64ydg8k5skof1.png,,21,20,False,0.82,https://www.reddit.com/r/wallstreetbets/commen...,$PSKY $17 Calls Expiring Tomorrow,[PSKY]
47,wallstreetbets,1nebocm,OTM-Bagboy9,1757604147,$SBET Holding til $100,Yep.. that’s me. You’re probably wondering how...,https://www.reddit.com/gallery/1nebocm,Yep.. that’s me. You’re probably wondering how...,20,26,False,0.75,https://www.reddit.com/r/wallstreetbets/commen...,$SBET Holding til $100Yep.. that’s me. You’re ...,[SBET]
48,wallstreetbets,1neikay,medsuchahassle,1757619963,Open yolo,Have been trading open in and out over the pas...,https://www.reddit.com/gallery/1neikay,Have been trading open in and out over the pas...,20,6,False,0.83,https://www.reddit.com/r/wallstreetbets/commen...,Open yoloHave been trading open in and out ove...,[]
49,wallstreetbets,1neb1k3,Clubpenguin8888,1757602628,$UNH $49k gain,"An update from my last post, I bought $UNH at ...",https://i.redd.it/anc2aprzujof1.jpeg,"An update from my last post, I bought $UNH at ...",18,5,False,0.88,https://www.reddit.com/r/wallstreetbets/commen...,"$UNH $49k gainAn update from my last post, I b...",[UNH]

In [34]:
cmts = sc.fetch_top_comments("1ndwms0")
cmts

,submission id,comment id,author,body,score,permalink,parent
0,1ndwms0,ndk8p7v,VisualMod,\n**User Report**| | | |\n:--|:--|:--|:--\n**T...,1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
1,1ndwms0,ndka9pv,tea_is_fyre,"You held on when you were down 70%, you deserv...",5192,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
2,1ndwms0,ndk9fh0,Options-n-Hookers,From OPEN my asshole to OPEN my wallet. \n\nCo...,3550,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
3,1ndwms0,ndkaghr,Redfield11,Now see this is beautiful because you had a co...,906,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
4,1ndwms0,ndka2wz,Megaloman-_-,https://preview.redd.it/y7yd12k31gof1.jpeg?wid...,745,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
...,...,...,...,...,...,...,...
267,1ndwms0,ndleesc,crykil,Love to see it,1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
268,1ndwms0,ndlejzr,According_Effort_878,Congrats OP!\n\nNow go buy yourself some quali...,1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
269,1ndwms0,ndleu2p,Rabbit-Quiet,"honestly that takes conviction, congrats. noth...",1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
270,1ndwms0,ndlfeum,bootlegSkynet,Your money has an open door policy.,1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0
271,1ndwms0,ndlflqw,ppkao,This is diamond hands on a whole different lev...,1,https://www.reddit.com/r/wallstreetbets/commen...,t3_1ndwms0

In [30]:
sample = posts_df["content"][1]
tokens = nltk.word_tokenize(sample)
tagged = nltk.pos_tag(tokens)
entities = nltk.chunk.ne_chunk(tagged)

In [31]:
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

In [32]:
sia.polarity_scores(sample)

{'neg': 0.0, 'neu': 0.846, 'pos': 0.154, 'compound': 0.9176}